# Generated by Django 5.1.1 on 2024-09-16 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/profile_pictures/')),
                ('futsal_image_1', models.ImageField(upload_to='images/futsal_images/')),
                ('futsal_image_2', models.ImageField(blank=True, null=True, upload_to='images/futsal_images/')),
                ('futsal_image_3', models.ImageField(blank=True, null=True, upload_to='images/futsal_images/')),
                ('futsal_image_4', models.ImageField(blank=True, null=True, upload_to='images/futsal_images/')),
                ('location', models.CharField(max_length=400)),
                ('google_maps_link', models.URLField(blank=True, null=True)),
                ('a_side', models.CharField(max_length=10)),
                ('grounds', models.IntegerField()),
                ('shower_facility', models.BooleanField(default=False)),
                ('parking_space', models.BooleanField(default=False)),
                ('changing_room', models.BooleanField(default=False)),
                ('restaurant', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
