# Generated by Django 5.1.1 on 2024-09-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_remove_userprofile_id_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='futsal_description',
            field=models.TextField(default=''),
        ),
    ]
