# Generated by Django 5.1.1 on 2024-12-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_userprofile_futsal_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='changing_room',
            new_name='is_futsal_admin',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='parking_space',
            new_name='is_verified',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='a_side',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='futsal_description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='futsal_image_1',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='futsal_image_2',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='futsal_image_3',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='futsal_image_4',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='google_maps_link',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='grounds',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='shower_facility',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='wifi',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_address',
            field=models.EmailField(default='adamya@getintoto.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
