# Generated by Django 5.1.1 on 2025-04-03 04:01

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Futsal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('futsal_name', models.CharField(max_length=200)),
                ('futsal_phone_number', models.BigIntegerField(default=9841111111)),
                ('futsal_image_1', models.ImageField(upload_to='images/futsal_images/')),
                ('futsal_image_2', models.ImageField(blank=True, null=True, upload_to='images/futsal_images/')),
                ('futsal_image_3', models.ImageField(blank=True, null=True, upload_to='images/futsal_images/')),
                ('futsal_image_4', models.ImageField(blank=True, null=True, upload_to='images/futsal_images/')),
                ('futsal_image_5', models.ImageField(blank=True, null=True, upload_to='images/futsal_images/')),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_table', models.JSONField(blank=True, null=True)),
                ('location', models.CharField(max_length=400)),
                ('google_maps_link', models.URLField(blank=True, null=True)),
                ('a_side', models.CharField(max_length=10)),
                ('grounds', models.IntegerField()),
                ('shower_facility', models.BooleanField(default=False)),
                ('parking_space', models.BooleanField(default=False)),
                ('changing_room', models.BooleanField(default=False)),
                ('restaurant', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('open_ground', models.BooleanField(default=False)),
                ('futsal_description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Futsal Description')),
                ('featured_futsal', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('futsal_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_date', models.DateField()),
                ('booking_start_time', models.TimeField()),
                ('booking_end_time', models.TimeField()),
                ('booking_status', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('futsal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='futsal.futsal')),
            ],
        ),
        migrations.CreateModel(
            name='Matchmaking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, choices=[('waiting', 'Waiting'), ('matched', 'Matched')], default='waiting', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_1', to=settings.AUTH_USER_MODEL)),
                ('player_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
