# Generated by Django 5.1.1 on 2025-04-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
