# Generated by Django 5.1.1 on 2024-12-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0002_futsal_alter_booking_futsal'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='open_ground',
            field=models.BooleanField(default=False),
        ),
    ]
