# Generated by Django 5.1.1 on 2024-12-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0003_booking_open_ground'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='open_ground',
        ),
        migrations.AddField(
            model_name='futsal',
            name='open_ground',
            field=models.BooleanField(default=False),
        ),
    ]
