# Generated by Django 5.1.1 on 2024-12-11 07:37

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0005_remove_booking_booking_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futsal',
            name='futsal_description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
