# Generated by Django 5.1.1 on 2025-01-21 11:04

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0006_alter_futsal_futsal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='futsal',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='futsal',
            name='price_table',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Price Table'),
        ),
        migrations.AlterField(
            model_name='futsal',
            name='futsal_description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Futsal Description'),
        ),
    ]
