# Generated by Django 5.1.1 on 2025-01-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0007_futsal_price_per_hour_futsal_price_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='futsal',
            name='futsal_phone_number',
            field=models.BigIntegerField(default=9841111111),
        ),
    ]
