# Generated by Django 5.1.1 on 2025-02-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0010_matchmaking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchmaking',
            name='status',
            field=models.CharField(blank=True, choices=[('waiting', 'Waiting'), ('matched', 'Matched')], default='waiting', max_length=20, null=True),
        ),
    ]
