# Generated by Django 5.1.1 on 2025-02-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0012_remove_matchmaking_player_matchmaking_player_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchmaking',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
